apiVersion: batch/v1
kind: Job
metadata:
  name: frontend-loadtest
  namespace: talentlink-local
spec:
  template:
    spec:
      hostAliases:
        - ip: "192.168.49.2"  # Replace with your `minikube ip`
          hostnames:
            - "talentlink.local"
      containers:
        - name: k6
          image: grafana/k6:latest
          command:
            - "k6"
            - "run"
            - "--summary-export=/output/frontend_result.json"
            - "/scripts/frontend_loadtest.js"
          volumeMounts:
            - name: test-scripts
              mountPath: /scripts
            - name: test-results
              mountPath: /output
      restartPolicy: Never
      volumes:
        - name: test-scripts
          configMap:
            name: frontend-test-scripts
        - name: test-results
          hostPath:
            path: /data/results
            type: DirectoryOrCreate
