apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: talentlink-local
spec:
  type: ClusterIP
  selector:
    app: matching-service
  ports:
    - port: 5000
      targetPort: 5000
